spring:
  datasource:
    url: {URL_DATABASE}
    username: {USERNAME_DATABASE}
    password: {PASSWORD_DATABASE}

  jpa:
    hibernate:
      ddl-auto: validate
    show_sql: true
    properties:
      hibernate:
        format_sql: true

server:
  error:
    include-message: always

jwt:
  public:
    key: {PUBLIC_KEY_PATH}
  private:
    key: {PRIVATE_KEY_PATH}
