spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ghe_chatbot_db
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: validate
    show_sql: true
    properties:
      hibernate:
        format_sql: true

server:
  error:
    include-message: always

jwt:
  public:
    key: classpath:key.pub
  private:
    key: classpath:key.pem