CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	delete boolean default false,
    PRIMARY KEY (id)
);

CREATE TABLE chat (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(100) NOT NULL,
    user_id BIGINT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	delete boolean default false,
    CONSTRAINT fk_chat_user_id FOREIGN KEY (user_id) REFERENCES users(id),
    PRIMARY KEY (id)
);

CREATE TABLE message (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    chat_id BIGINT NOT NULL,
    text text NOT NULL,
	type varchar(50) not null,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	delete boolean default false,
    CONSTRAINT fk_message_chat_id FOREIGN KEY (chat_id) REFERENCES chat(id),
    CONSTRAINT ck_chat_type check (type in ('USER', 'BOT')),
    PRIMARY KEY (id)
);